"""Fetch the full card roster (costs + icons) from the official API.

Usage:
    export CR_API_TOKEN=...   # free key from developer.clashroyale.com
    .venv/bin/python scripts/fetch_cards.py [--icons]

Writes data/cards.json (same schema as the bundled sample, so it can be
passed to clash_copilot.cards.load_card_costs). With --icons, also downloads
each card's portrait to data/icons/<name>.png for use as real templates.
"""

import json
import os
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from clash_copilot.crapi import cards_payload_to_costs, fetch_json  # noqa: E402

DATA_DIR = Path(__file__).parent.parent / "data"


def main() -> None:
    token = os.environ.get("CR_API_TOKEN")
    if not token:
        sys.exit("Set CR_API_TOKEN (free key from developer.clashroyale.com)")

    payload = fetch_json("/cards", token)
    costs = cards_payload_to_costs(payload)
    DATA_DIR.mkdir(exist_ok=True)
    out = DATA_DIR / "cards.json"
    out.write_text(
        json.dumps(
            {"note": "Generated by scripts/fetch_cards.py", "cards": costs},
            indent=2,
            sort_keys=True,
        )
    )
    print(f"Wrote {len(costs)} card costs to {out}")

    if "--icons" in sys.argv:
        icons_dir = DATA_DIR / "icons"
        icons_dir.mkdir(exist_ok=True)
        for card in payload["items"]:
            url = card.get("iconUrls", {}).get("medium")
            if not url:
                continue
            target = icons_dir / f"{card['name']}.png"
            urllib.request.urlretrieve(url, target)
        print(f"Downloaded icons to {icons_dir}")


if __name__ == "__main__":
    main()
